// ─── WVE SEO: Estimate Explanation Block — Phase 12 ──────────────────────────
// Server component. Explains how the estimate was calculated and its limitations.
// Indexed by Google — no "use client".

import { getSeoContent } from "@/lib/value-engine/seoContent";
import type { EstimationType, VerticalSlug } from "@/lib/value-engine/types";

interface EstimateExplanationProps {
  type: EstimationType;
  vertical: VerticalSlug;
  serviceType?: string;
}

const TYPE_INTRO: Record<EstimationType, { label: string; description: string }> = {
  "service-estimate": {
    label: "How This Estimate Was Calculated",
    description:
      "Service estimates are generated by a formula model combining regional labour indices, materials cost benchmarks, and quality tier multipliers. The model is calibrated against contractor market data at the national and regional level.",
  },
  "market-value": {
    label: "How This Market Value Was Determined",
    description:
      "Market values are aggregated from multi-source marketplace data. Listings are weighted by source trust score, recency, and condition match. All values are normalised to USD.",
  },
  "appreciation": {
    label: "How Appreciation Is Estimated",
    description:
      "Appreciation estimates combine entity-specific historical resale performance with category-level demand indices. Results are indicative and not a guarantee of future value.",
  },
};

export default function EstimateExplanation({
  type,
  vertical,
  serviceType,
}: EstimateExplanationProps) {
  const content  = getSeoContent(serviceType, vertical);
  const typeInfo = TYPE_INTRO[type];

  return (
    <section
      aria-labelledby="estimate-explanation-heading"
      className="rounded-2xl border border-white/6 bg-white/2 p-6"
    >
      <h2
        id="estimate-explanation-heading"
        className="text-base font-semibold text-white mb-3"
      >
        {typeInfo.label}
      </h2>

      <p className="text-sm leading-relaxed text-gray-400 mb-4">
        {typeInfo.description}
      </p>

      {/* Specific method detail from content data */}
      {content.estimationMethod && (
        <div className="rounded-xl border border-white/6 bg-white/3 px-4 py-3 mb-4">
          <p className="text-[11px] font-medium text-gray-500 uppercase tracking-[0.18em] mb-1">
            Model detail
          </p>
          <p className="text-xs text-gray-400 leading-relaxed">
            {content.estimationMethod}
          </p>
        </div>
      )}

      {/* Limitations */}
      {content.limitations.length > 0 && (
        <div>
          <p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-gray-600 mb-2">
            Estimate Limitations
          </p>
          <ul className="space-y-1.5">
            {content.limitations.map((lim, i) => (
              <li key={i} className="flex items-start gap-2 text-xs text-gray-500 leading-relaxed">
                <span className="mt-0.5 h-1.5 w-1.5 shrink-0 rounded-full bg-gray-700" />
                {lim}
              </li>
            ))}
          </ul>
        </div>
      )}
    </section>
  );
}
